"""Exporta el contrato OpenAPI y sus tipos TypeScript de forma determinística."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.main import app

BACKEND_ROOT = Path(__file__).resolve().parents[2]
REPOSITORY_ROOT = BACKEND_ROOT.parent
OPENAPI_PATH = BACKEND_ROOT / "openapi.json"
TYPESCRIPT_PATH = REPOSITORY_ROOT / "front/src/generated/openapi.ts"


def _typescript_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return reference.rsplit("/", 1)[-1]

    any_of = schema.get("anyOf")
    if isinstance(any_of, list):
        return " | ".join(_typescript_type(item) for item in any_of)

    all_of = schema.get("allOf")
    if isinstance(all_of, list):
        return " & ".join(_typescript_type(item) for item in all_of)

    values = schema.get("enum")
    if isinstance(values, list):
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in values)

    schema_type = schema.get("type")
    if schema_type == "array":
        return f"Array<{_typescript_type(schema.get('items', {}))}>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_typescript_type(additional)}>"
        properties = schema.get("properties")
        if isinstance(properties, dict):
            required = set(schema.get("required", []))
            fields = [
                f"{json.dumps(name)}{' ' if name in required else '?'}: {_typescript_type(value)}"
                for name, value in properties.items()
            ]
            return "{ " + "; ".join(fields) + " }"
        return "Record<string, unknown>"
    return "unknown"


def _typescript_contract(schema: dict[str, Any]) -> str:
    components = schema.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by `python -m app.scripts.export_openapi`. Do not edit.",
        "",
    ]
    for name, definition in sorted(components.items()):
        if definition.get("type") == "object" and isinstance(definition.get("properties"), dict):
            required = set(definition.get("required", []))
            lines.append(f"export interface {name} {{")
            for field_name, field_schema in definition["properties"].items():
                optional = "" if field_name in required else "?"
                lines.append(
                    f"  {json.dumps(field_name)}{optional}: {_typescript_type(field_schema)}"
                )
            lines.append("}")
        else:
            lines.append(f"export type {name} = {_typescript_type(definition)}")
        lines.append("")
    return "\n".join(lines)


def _expected_files() -> dict[Path, str]:
    schema = app.openapi()
    return {
        OPENAPI_PATH: json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        TYPESCRIPT_PATH: _typescript_contract(schema),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for path, expected in _expected_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(REPOSITORY_ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    if stale:
        parser.error(
            "contrato desactualizado: "
            + ", ".join(stale)
            + "; ejecutar `cd back && uv run python -m app.scripts.export_openapi`"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
